version: "3.1"

########################### EXTENSION FIELDS
x-environment: &default-tz-puid-pgid
  TZ: America/Chicago
  PUID: 1000
  PGID: 1000

x-common-keys: &common-keys
  environment:
    <<: *default-tz-puid-pgid
  restart: unless-stopped
  deploy:
    mode: replicated
    replicas: 1
########################### EXTENSION FIELDS

services:
  prowlarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    volumes:
      - prowlarr:/config
    ports:
      - 9696:9696

  radarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - radarr:/config
      - movies:/movies #optional
      #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878

  sonarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - sonarr:/config
      - tv:/tv #optional
      #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989

  lidarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - lidarr:/config
      - music:/music #optional
      #- /path/to/downloads:/downloads #optional
    ports:
      - 8686:8686

  readarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    volumes:
      - readarr:/config
      - books:/books #optional
      #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8787:8787

volumes:
  prowlarr:
    name: prowlarr
    driver_opts:
      type: nfs
      o: addr=10.10.10.139,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/tank/swarm/prowlarr
  radarr:
    name: radarr
    driver_opts:
      type: nfs
      o: addr=10.10.10.139,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/tank/swarm/radarr
  sonarr:
    name: sonarr
    driver_opts:
      type: nfs
      o: addr=10.10.10.139,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/tank/swarm/sonarr
  lidarr:
    name: lidarr
    driver_opts:
      type: nfs
      o: addr=10.10.10.139,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/tank/swarm/lidarr
  readarr:
    name: readarr
    driver_opts:
      type: nfs
      o: addr=10.10.10.139,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/tank/swarm/readarr
  movies:
    name: movies
    driver_opts:
      type: nfs
      o: addr=10.10.10.139,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/tank/swarm/media/movies
  music:
    name: music
    driver_opts:
      type: nfs
      o: addr=10.10.10.139,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/tank/swarm/media/music
  tv:
    name: tv
    driver_opts:
      type: nfs
      o: addr=10.10.10.139,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/tank/swarm/media/tv
  books:
    name: books
    driver_opts:
      type: nfs
      o: addr=10.10.10.139,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: :/mnt/tank/swarm/media/books
