#privelaged Docker LXC container with cifs-utils installed
# create the directories
#
# mkdir -p docker/{docker_configs/{prowlarr,radarr,sonarr,lidarr,readarr},docker_media/{movies,tvseries,music,books}}
#
#mkdir /docker/docker_configs
#                /prowlarr
#                /radarr
#                /sonarr
#                /lidarr
#                /readarr
#mkdir /docker/docker_media
#                /movies
#                /tvseries
#                /music
#                /books
##########
#
#   still need to setup a VPN and add depends-on to each of the services.
#
##########

version: "2.1"

########################### EXTENSION FIELDS
x-environment: &default-tz-puid-pgid
  TZ: TZ=America/Chicago
  PUID: PUID=1000
  PGID: PGID=1000

x-common-keys: &common-keys
  environment:
    <<: *default-tz-puid-pgid
  restart: unless-stopped
########################### EXTENSION FIELDS

services:
  prowlarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    volumes:
      - /docker/docker_configs/prowlarr:/config
    ports:
      - 9696:9696

  radarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /docker/docker_configs/radarr:/config
      - /docker/docker_media/movies:/movies #optional
      #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878

  sonarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /docker/docker_configs/sonarr:/config
      - /docker/docker_media/tvseries:/tv #optional
      #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989

  lidarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - /docker/docker_configs/lidarr:/config
      - /docker/docker_media/music:/music #optional
      #- /path/to/downloads:/downloads #optional
    ports:
      - 8686:8686

  readarr:
    <<: *common-keys # See EXTENSION FIELDS
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    volumes:
      - /docker/docker_configs/readarr:/config
      - /docker/docker_media/books:/books #optional
      #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8787:8787
